### ISSUE TITLE
doc.rust-kr.org 도메인에 ghpage 연결

### ISSUE THREAD

**Issue by rinthel** [rust-kr/doc.rust-kr.org#1]
- 현재 빌드된 ghpage는 기본 주소인 https://rust-kr.github.io/doc.rust-kr.org 로 연결되어 있습니다
- 이 페이지를 https://doc.rust-kr.org 로 연결하고 관련한 링크를 수정하는 작업이 필요한 상태입니다

**Comment by sh-cho** [comment]
제가 작업해도 될까요? 도메인이랑 리파지토리 권한만 주시면 바로 할 수 있을 것 같습니다

**Comment by rinthel** [comment]
@sh-cho 이슈 컨트리뷰팅에 관심 주셔서 감사드립니다! 저도 이 레포 수정 권한만 있는지라, 관리자분께 문의를 해보고 말씀드릴게요 ㅎㅎ

**Comment by simnalamburt** [comment]
Done https://doc.rust-kr.org/

**Comment by simnalamburt** [comment]
rust-kr.org 메인에도 반영하였고: https://github.com/rust-kr/rust-kr.org/commit/5f0cb145eda7ff1715b93aabf3f7911f14de9916

doc.rust-kr.org 메인에도 반영하였습니다: https://github.com/rust-kr/doc.rust-kr.org/commit/b4ed292a06f2ff283ed73e41f184fca0af27754b

**Comment by rinthel** [comment]
감사합니다!

**Comment by simnalamburt** [comment]
@rinthel custom domain을 적용하기위해 gh-pages에 CNAME 파일을 지금 수동으로 넣은 상태인데, 다음 빌드때에 저 파일이 날아갈거같습니다. CNAME 파일이 매 빌드마다 자동으로 추가되도록 설정을 고쳐야할거같은데 지금 제가 TRPL 스택이 익숙치않아서 어떻게하는지 모르겠네요. 혹시 임의의 static file 추가하는 방법이 여기 있을까요?

**Comment by simnalamburt** [comment]
스스로 해결했습니다. https://github.com/rust-kr/doc.rust-kr.org/commit/1ec88fb250a882c639e99e66080506deaf0ae80d

**Comment by rinthel** [comment]
와우 감사합니다 🤗

**Comment by sh-cho** [comment]
인증서 확인 부탁드립니다~

```sh
$ openssl s_client -connect doc.rust-kr.org:443 | openssl x509 -noout -enddate
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert TLS RSA SHA256 2020 CA1
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = *.github.io
verify return:1
notAfter=Mar 20 23:59:59 2024 GMT
```

https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

enforce https 옵션만 켜주시면 됩니다

**Comment by simnalamburt** [comment]
Custom domain에 대해선 enforce https를 못켭니다

**Comment by sh-cho** [comment]
https://github.blog/2018-05-01-github-pages-custom-domains-https/

이때부터 됩니다 ㅎㅎ

**Comment by simnalamburt** [comment]
![image](https://github.com/rust-kr/doc.rust-kr.org/assets/4435445/8d189974-b732-4a24-b379-d47f22c5b498)

https 문제가 해결되진 않은거같지만 켰습니다

**Comment by sh-cho** [comment]
doc.rust-kr.org A 레코드 대신 CNAME 레코드 넣어주시면 될 것 같습니다 (아마도;)

**Comment by simnalamburt** [comment]
이미 CNAME으로 되어있고, 아니었다고 쳐도 이건 인증서 발급에 영향을 주지 않아야 정상일거같습니다.

**Comment by sh-cho** [comment]
https://github.com/isaacs/github/issues/1675

www CNAME도 추가해줘야 하는 것 같네요 한번 부탁드립니다

**Comment by simnalamburt** [comment]
@sh-cho doc.rust-kr.org 는 apex domain이 아니어서 저 이슈에 해당하지 않을거같은데.. www.doc.rust-kr.org 에 CNAME을 설정해달라는 말인가요?

참고로 www.rust-kr.org 는 rust-kr.org와 같은곳을 가리키도록 세팅되어있습니다.

**Comment by sh-cho** [comment]
아 아닙니다. `www.rust-kr.org -> rust-kr.github.io` 말씀드린겁니다

**Comment by simnalamburt** [comment]
참고로 [www.rust-kr.org](http://www.rust-kr.org/) 는 rust-kr.org와 같은곳을 가리키도록 세팅되어있습니다. (2)
